apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
      tier: database
  template:
    metadata:
      labels:
        app: wordpress-mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        envFrom:
        - secretRef: 
            name: mysql-env-secret
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-pvc
