apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: mysql-storage
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # the path exposed on server
    path: /tmp/data
    server: 192.168.1.4
