apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: mysql-storage
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # the path exposed on server
    path: /tmp/data/mysql
    server: 192.168.1.4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: wordpress-storage
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # the path exposed on server
    path: /tmp/data/wordpress
    server: 192.168.1.4
