apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  storageClassName: wordpress-storage
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteOnce
