namePrefix: staging-
commonLabels:
  variant: staging
resources:
- ../../base

# modify base configurations
patches:
- path: redis-pod-patch.yaml
  target:
    kind: Pod
    name: redis

# add items to base configurations
patchesStrategicMerge:
- redis-pod_add_env.yaml
