apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:6.0
    envFrom:
    - configMapRef:
        name: redis-env
    args: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    resources: 
      limits:
        cpu: 0.1
    ports:
    - name: redis
      containerPort: 6379
    volumeMounts:
    - name: data
      mountPath: /data
    - name: config
      mountPath: /usr/local/etc/redis
  volumes:
  - name: data
    emptyDir: {}
  - name: config
    configMap:
      name: redis-config
      items:
      - key: my-redis.conf
        path: redis.conf
